spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.18.0.2:31336/authezat
    username: local
    password: 1234

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

logging:
  level:
    org:
      springframework:
        web: debug

springdoc:
  api-docs:
    enabled: true