spring:
  application:
    name: authezat

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.18.0.2:31336/authezat
    username: local
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true